services:
  # From PS 1.7.0 to PS 1.7.3, the bundled version of Symfony is 2.x on which the _defaults
  # key is invalid. To prevent error on these versions, each service has to be specifically
  # declared as public.
  #  _defaults:
  #   public: true
  flavioski.module.salusperaquam.repository.treatment_repository:
    class: Flavioski\Module\SalusPerAquam\Repository\TreatmentRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Flavioski\Module\SalusPerAquam\Entity\Treatment

  flavioski.module.salusperaquam.treatments.install:
    class: Flavioski\Module\SalusPerAquam\Database\TreatmentInstaller
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
