# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/tabs/
#
# configuration
flavioski_salusperaquam_configuration_setting_index:
  path: /salusperaquam/configuration/setting
  methods: [GET]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\Configuration\SettingController::indexAction'
    _legacy_controller: 'AdminSalusperaquamConfigurationSetting'
    _legacy_link: 'AdminSalusperaquamConfigurationSetting'

flavioski_salusperaquam_configuration_setting_save:
  path: /salusperaquam/configuration/setting
  methods: [POST]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\Configuration\SettingController::processFormAction'
    _legacy_controller: 'AdminSalusperaquamConfigurationSetting'
    _legacy_link: 'AdminSalusperaquamConfigurationSetting:update'

flavioski_salusperaquam_configuration_access_index:
  path: /salusperaquam/configuration/access
  methods: [GET]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\Configuration\AccessController::indexAction'
    _legacy_controller: 'AdminSalusperaquamConfigurationAccess'
    _legacy_link: 'AdminSalusperaquamConfigurationAccess'

flavioski_salusperaquam_configuration_access_save:
  path: /salusperaquam/configuration/access
  methods: [POST]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\Configuration\AccessController::processFormAction'
    _legacy_controller: 'AdminSalusperaquamConfigurationAccess'
    _legacy_link: 'AdminSalusperaquamConfigurationAccess:update'

flavioski_salusperaquam_configuration_user_index:
  path: /salusperaquam/configuration/user
  methods: [GET]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\Configuration\UserController::indexAction'
    _legacy_controller: 'AdminSalusperaquamConfigurationUser'
    _legacy_link: 'AdminSalusperaquamConfigurationUser'

flavioski_salusperaquam_configuration_user_save:
  path: /salusperaquam/configuration/user
  methods: [POST]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\Configuration\UserController::processFormAction'
    _legacy_controller: 'AdminSalusperaquamConfigurationUser'
    _legacy_link: 'AdminSalusperaquamConfigurationUser:update'

flavioski_salusperaquam_configuration_treatment_index:
  path: /salusperaquam/configuration/treatment
  methods: [GET]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\Configuration\TreatmentController::indexAction'
    _legacy_controller: 'AdminSalusperaquamConfigurationTreatment'
    _legacy_link: 'AdminSalusperaquamConfigurationTreatment'

flavioski_salusperaquam_configuration_treatment_save:
  path: /salusperaquam/configuration/treatment
  methods: [POST]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\Configuration\TreatmentController::processFormAction'
    _legacy_controller: 'AdminSalusperaquamConfigurationTreatment'
    _legacy_link: 'AdminSalusperaquamConfigurationTreatment:update'

# treatments
flavioski_salusperaquam_treatment_index:
  path: /salusperaquam/treatments/{offset}/{limit}/{orderBy}/{sortOrder}
  methods: [GET]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\TreatmentController::indexAction'
    _legacy_controller: 'AdminSalusperaquamTreatment'
    _legacy_link: 'AdminSalusperaquamTreatment'
    limit: last
    offset: 0
    orderBy: last
    sortOrder: last
  requirements:
    limit: _limit|last|\d+
    orderBy: last|id_product|name|code|price|active
    offset: last|\d+
    sortOrder: last|asc|desc

flavioski_salusperaquam_treatment_search:
  path: /salusperaquam/treatments
  methods: [POST]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\TreatmentController::searchAction'
    _legacy_controller: 'AdminSalusperaquamTreatment'
    _legacy_link: 'AdminSalusperaquamTreatment:search'

flavioski_salusperaquam_treatment_generate:
  path: /salusperaquam/generate
  methods: [GET, POST]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\TreatmentController::generateAction'
    _legacy_controller: 'AdminSalusperaquamTreatment'
    _legacy_link: 'AdminSalusperaquamTreatment:generate'

flavioski_salusperaquam_treatment_sync:
  path: /salusperaquam/syncronize
  methods: [GET, POST]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\TreatmentController::syncAction'
    _legacy_controller: 'AdminSalusperaquamTreatment'
    _legacy_link: 'AdminSalusperaquamTreatment:sync'

flavioski_salusperaquam_treatment_create:
  path: /salusperaquam/treatments/new
  methods: [GET, POST]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\TreatmentController::createAction'
    _legacy_controller: 'AdminSalusperaquamTreatment'
    _legacy_link: 'AdminSalusperaquamTreatment:add'

flavioski_salusperaquam_treatment_edit:
  path: /salusperaquam/treatments/{treatmentId}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\TreatmentController::editAction'
    _legacy_controller: 'AdminSalusperaquamTreatment'
    _legacy_link: 'AdminSalusperaquamTreatment:update'
  requirements:
    treatmentId: \d+

flavioski_salusperaquam_treatment_delete:
  path: /salusperaquam/treatments/{treatmentId}/delete
  methods: [DELETE]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\TreatmentController::deleteAction'
    _legacy_controller: 'AdminSalusperaquamTreatment'
    _legacy_link: 'AdminSalusperaquamTreatment:deletetreatment'
  requirements:
    treatmentId: \d+

flavioski_salusperaquam_treatment_bulk_delete:
  path: /salusperaquam/treatments/bulkDelete
  methods: [POST]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\TreatmentController::deleteBulkAction'
    _legacy_controller: 'AdminSalusperaquamTreatment'
    _legacy_link: 'AdminSalusperaquamTreatment:submitBulkdeletetreatment'

flavioski_salusperaquam_treatment_toggle_status:
  path: /salusperaquam/treatments/{treatmentId}/toggle-status
  methods: [POST]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\TreatmentController::toggleStatusAction'
    _legacy_controller: 'AdminSalusperaquamTreatment'
    _legacy_link: 'AdminSalusperaquamTreatment:statustreatment'
    _legacy_parameters:
      id_treatment: treatmentId
  requirements:
    treatmentId: \d+

# product combinations
flavioski_salusperaquam_product_combinations:
  path: /salusperaquam/product/combinations
  methods: [GET]
  defaults:
    _controller: 'Flavioski\Module\SalusPerAquam\Controller\Admin\ProductController::getCombinationsAction'
    _legacy_controller: 'AdminSalusperaquamProduct'
    _legacy_link: 'AdminSalusperaquamProduct:getCombinations'
