# main services
imports:
  - { resource: ./common.yml }

services:
  # Form services
  flavioski.module.salusperaquam.type.configuration:
    class: 'Flavioski\Module\SalusPerAquam\Form\ConfigurationType'
    parent: 'form.type.translatable.aware'
    arguments:
      - '@=service("prestashop.adapter.multistore_feature").isUsed()'
    tags:
      - { name: form.type }

  flavioski.module.salusperaquam.type.treatment:
    class: 'Flavioski\Module\SalusPerAquam\Form\TreatmentType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  flavioski.module.salusperaquam.type.treatment_rate:
    class: 'Flavioski\Module\SalusPerAquam\Form\TreatmentRateType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - '@flavioski.module.salusperaquam.form.choice_provider.product_attribute_by_id'
      - '@=service("prestashop.adapter.data_provider.currency").getDefaultCurrency()'
      - '@router'
    tags:
      - { name: form.type }

  flavioski.module.salusperaquam.type.product_choice:
    class: 'Flavioski\Module\SalusPerAquam\Form\Type\ProductChoiceType'
    arguments:
      - '@flavioski.module.salusperaquam.form.choice_provider.product_by_id'
      - '@flavioski.module.salusperaquam.form.choice_provider.product_by_id'
    tags:
      - { name: form.type }

  flavioski.module.salusperaquam.form.choice_provider.product_by_id:
    class: 'Flavioski\Module\SalusPerAquam\Form\ChoiceProvider\ProductByIdChoiceProvider'
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getLanguage().id'

  flavioski.module.salusperaquam.form.choice_provider.product_attribute_by_id:
    class: 'Flavioski\Module\SalusPerAquam\Form\ChoiceProvider\ProductAttributeByIdChoiceProvider'

  flavioski.module.salusperaquam.domain.product.product_required_fields_provider:
    class: 'Flavioski\Module\SalusPerAquam\Domain\Product\ProductRequiredFieldsProvider'
    arguments:
      - '@prestashop.adapter.attribute.repository.attribute_repository'

  flavioski.module.salusperaquam.form.identifiable_object.data_provider.configuration_form_handler:
    class: 'Flavioski\Module\SalusPerAquam\Form\ConfigurationFormDataHandler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@flavioski.module.salusperaquam.form.identifiable_object.data_provider.configuration_data_provider'
      - 'Flavioski\Module\SalusPerAquam\Form\ConfigurationType'
      - 'ConfigurationPage'
    calls:
      - method: setTabRepository
        arguments:
           - '@prestashop.core.admin.tab.repository'

  flavioski.module.salusperaquam.form.identifiable_object.data_provider.configuration_data_provider:
    class: 'Flavioski\Module\SalusPerAquam\Form\ConfigurationFormDataProvider'
    arguments:
      - '@flavioski.module.salusperaquam.adapter.salusperaquam_configuration'
      - '@translator'

  flavioski.module.salusperaquam.form.identifiable_object.data_provider.treatment_form_data_provider:
    class: 'Flavioski\Module\SalusPerAquam\Form\TreatmentFormDataProvider'
    arguments:
      - '@flavioski.module.salusperaquam.repository.treatment_repository'

  flavioski.module.salusperaquam.form.identifiable_object.builder.treatment_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Flavioski\Module\SalusPerAquam\Form\TreatmentType'
      - '@flavioski.module.salusperaquam.form.identifiable_object.data_provider.treatment_form_data_provider'

  flavioski.module.salusperaquam.form.identifiable_object.data_handler.treatment_form_data_handler:
    class: 'Flavioski\Module\SalusPerAquam\Form\TreatmentFormDataHandler'
    arguments:
      - '@flavioski.module.salusperaquam.repository.treatment_repository'
      - '@prestashop.core.admin.lang.repository'
      - '@doctrine.orm.default_entity_manager'

  flavioski.module.salusperaquam.form.identifiable_object.handler.treatment_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@flavioski.module.salusperaquam.form.identifiable_object.data_handler.treatment_form_data_handler'

  flavioski.module.salusperaquam.form.identifiable_object.data_provider.treatment_rate_form_data_provider:
    class: 'Flavioski\Module\SalusPerAquam\Form\TreatmentRateFormDataProvider'
    arguments:
      - '@flavioski.module.salusperaquam.repository.treatment_rate_repository'

  flavioski.module.salusperaquam.form.identifiable_object.builder.treatment_rate_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Flavioski\Module\SalusPerAquam\Form\TreatmentRateType'
      - '@flavioski.module.salusperaquam.form.identifiable_object.data_provider.treatment_rate_form_data_provider'

  flavioski.module.salusperaquam.form.identifiable_object.data_handler.treatment_rate_form_data_handler:
    class: 'Flavioski\Module\SalusPerAquam\Form\TreatmentRateFormDataHandler'
    arguments:
      - '@flavioski.module.salusperaquam.repository.treatment_rate_repository'
      - '@doctrine.orm.default_entity_manager'

  flavioski.module.salusperaquam.form.identifiable_object.handler.treatment_rate_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@flavioski.module.salusperaquam.form.identifiable_object.data_handler.treatment_rate_form_data_handler'

  # Adapter
  flavioski.module.salusperaquam.adapter.salusperaquam_configuration:
    class: 'Flavioski\Module\SalusPerAquam\Adapter\SalusperaquamConfiguration'
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  # Grid services
  flavioski.module.salusperaquam.grid.definition.factory.treatments:
    class: 'Flavioski\Module\SalusPerAquam\Grid\Definition\Factory\TreatmentGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    arguments:
      - "@=service('router').generate('admin_common_reset_search', {'controller': 'treatment', 'action': 'index'})"
      - "@=service('router').generate('flavioski_salusperaquam_treatment_index')"

  flavioski.module.salusperaquam.grid.query_builder.treatment:
    class: 'Flavioski\Module\SalusPerAquam\Grid\Query\TreatmentQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"

  flavioski.module.salusperaquam.grid.data_provider.treatments:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@flavioski.module.salusperaquam.grid.query_builder.treatment'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'treatment'

  flavioski.module.salusperaquam.grid.factory.treatments:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@flavioski.module.salusperaquam.grid.definition.factory.treatments'
      - '@flavioski.module.salusperaquam.grid.data_provider.treatments'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  # Generator service
  flavioski.module.salusperaquam.treatments.generator:
    class: 'Flavioski\Module\SalusPerAquam\Database\TreatmentGenerator'
    arguments:
      - '@flavioski.module.salusperaquam.repository.treatment_repository'
      - '@prestashop.core.admin.lang.repository'
      - '@doctrine.orm.default_entity_manager'

  # Sync service
  flavioski.module.salusperaquam.treatments.sync:
    class: 'Flavioski\Module\SalusPerAquam\Database\TreatmentSync'
    arguments:
    - '@flavioski.module.salusperaquam.repository.treatment_repository'
    - '@flavioski.module.salusperaquam.repository.treatment_rate_repository'
    - '@prestashop.core.admin.lang.repository'
    - '@doctrine.orm.default_entity_manager'
    - '@flavioski.module.salusperaquam.webservice.get.treatment'

  # CQRS pattern toggle status
  flavioski.module.salusperaquam.treatments.domain.treatment.query_handler.get_treatment_is_active_treatment_handler:
    class: 'Flavioski\Module\SalusPerAquam\Domain\Treatment\QueryHandler\GetTreatmentIsActiveHandler'
    arguments:
      - '@flavioski.module.salusperaquam.repository.treatment_repository'
    tags:
      - name: tactician.handler
        command: 'Flavioski\Module\SalusPerAquam\Domain\Treatment\Query\GetTreatmentIsActive'

  flavioski.module.salusperaquam.treatments.domain.treatment.command_handler.toggle_is_active_treatment_handler:
    class: 'Flavioski\Module\SalusPerAquam\Domain\Treatment\CommandHandler\ToggleIsActiveTreatmentHandler'
    arguments:
      - '@flavioski.module.salusperaquam.repository.treatment_repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - name: tactician.handler
        command: 'Flavioski\Module\SalusPerAquam\Domain\Treatment\Command\ToggleIsActiveTreatmentCommand'

  # Constraint validator
  flavioski.module.salusperaquam.constraint_validator.treatment_product_attribute_validator:
    class: 'Flavioski\Module\SalusPerAquam\ConstraintValidator\TreatmentProductAttributeRequiredValidator'
    arguments:
      - '@flavioski.module.salusperaquam.domain.product.product_required_fields_provider'
    tags:
      - { name: validator.constraint_validator }

  # Product query handler
  flavioski.module.salusperaquam.domain.product.query_handler.get_product_required_fields:
    class: 'Flavioski\Module\SalusPerAquam\Domain\Product\QueryHandler\GetProductRequiredFieldsHandler'
    arguments:
      - '@flavioski.module.salusperaquam.domain.product.product_required_fields_provider'
    tags:
      - name: tactician.handler
        command: 'Flavioski\Module\SalusPerAquam\Domain\Product\Query\GetProductRequiredFields'

  # Web Service
  flavioski.module.salusperaquam.webservice.my_web_service:
    class: 'Flavioski\Module\SalusPerAquam\WebService\MyWebService'
    arguments: #['@prestashop.adapter.legacy.configuration']
      - "@=service('prestashop.adapter.legacy.configuration').getBoolean('SALUSPERAQUAM_CONFIGURATION_TEST')"
      - "@=service('prestashop.adapter.legacy.configuration').get('SALUSPERAQUAM_CONFIGURATION_TEST_URL')"
      - "@=service('prestashop.adapter.legacy.configuration').get('SALUSPERAQUAM_CONFIGURATION_TEST_USERNAME')"
      - "@=service('prestashop.adapter.legacy.configuration').get('SALUSPERAQUAM_CONFIGURATION_TEST_PASSWORD')"
      #- "@=service('prestashop.adapter.legacy.configuration').get('SALUSPERAQUAM_CONFIGURATION_TEST_RESOURCE_GET_TREATMENT')"
      #- "@=service('prestashop.adapter.legacy.configuration').get('SALUSPERAQUAM_CONFIGURATION_TEST_RESOURCE_ADD_SALE')"
      - "@=service('prestashop.adapter.legacy.configuration').getBoolean('SALUSPERAQUAM_CONFIGURATION_PRODUCTION')"
      - "@=service('prestashop.adapter.legacy.configuration').get('SALUSPERAQUAM_CONFIGURATION_PRODUCTION_URL')"
      - "@=service('prestashop.adapter.legacy.configuration').get('SALUSPERAQUAM_CONFIGURATION_PRODUCTION_USERNAME')"
      - "@=service('prestashop.adapter.legacy.configuration').get('SALUSPERAQUAM_CONFIGURATION_PRODUCTION_PASSWORD')"
      #- "@=service('prestashop.adapter.legacy.configuration').get('SALUSPERAQUAM_CONFIGURATION_PRODUCTION_RESOURCE_GET_TREATMENT')"
      #- "@=service('prestashop.adapter.legacy.configuration').get('SALUSPERAQUAM_CONFIGURATION_PRODUCTION_RESOURCE_ADD_SALE')"

  flavioski.module.salusperaquam.webservice.get.treatment:
    class: 'Flavioski\Module\SalusPerAquam\WebService\GetTreatment'
    arguments:
      - '@flavioski.module.salusperaquam.webservice.my_web_service'

  flavioski.module.salusperaquam.webservice.add.sale:
    class: 'Flavioski\Module\SalusPerAquam\WebService\AddSale'
    arguments:
      - '@flavioski.module.salusperaquam.webservice.my_web_service'

  # Command
  flavioski.module.salusperaquam.command.web_service_add_sale_command:
    class: Flavioski\Module\SalusPerAquam\Command\WebServiceAddSaleCommand
    arguments:
      - "@prestashop.adapter.legacy.logger"
      - "@translator"
      - "@doctrine.orm.entity_manager"
      - '@=service("prestashop.adapter.legacy.configuration").get("PS_LANG_DEFAULT")'
      - '@=service("prestashop.adapter.legacy.configuration").get("PS_SHOP_EMAIL")'
      - '@=service("prestashop.adapter.legacy.configuration").get("PS_SHOP_DEFAULT")'
      - '@flavioski.module.salusperaquam.webservice.add.sale'
    tags:
        - { name: 'console.command' }

  flavioski.module.salusperaquam.command.web_service_get_treatment_command:
    class: Flavioski\Module\SalusPerAquam\Command\WebServiceGetTreatmentCommand
    arguments:
      - "@prestashop.adapter.legacy.logger"
      - "@translator"
      - '@=service("prestashop.adapter.legacy.configuration").get("PS_LANG_DEFAULT")'
      - '@=service("prestashop.adapter.legacy.configuration").get("PS_SHOP_EMAIL")'
      - '@=service("prestashop.adapter.legacy.configuration").get("PS_SHOP_DEFAULT")'
      - '@flavioski.module.salusperaquam.treatments.sync'
    tags:
      - { name: 'console.command' }

  flavioski.module.salusperaquam.command.web_service_change_order_status_command:
    class: Flavioski\Module\SalusPerAquam\Command\WebServiceChangeOrderStatusCommand
    arguments:
      - "@prestashop.adapter.legacy.logger"
      - "@prestashop.adapter.legacy.context"
    tags:
      - { name: 'console.command' }
